version: '3'

services:

  frontend:
    image: nginx:alpine
    volumes:
      - ../frontend:/usr/share/nginx/html
    ports:
      - "9090:80"
    networks:
      - app-network

  user-db:
    image: mongo
    volumes:
      - user_data:/data/db
    networks:
      - app-network

  product-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: productdb
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - app-network

  cache:
    image: redis
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - app-network

volumes:
  user_data:
  product_data:

networks:
  app-network: